locale: en
RealServer: false
Debug_Mode: INFO
SQL:
  Database: server_hangout
  Hangout:
    IP: localhost
    Username: admin
    Password: password
  Local:
    IP: localhost
    Username: root
    Password: ''